# CODE THAT IS GENERATED BY CHAT GPT

import json
from pyproj import Transformer
import os

# Define the folder path
folder_path = "./given_data/cityline_geojson"

# Ensure the output folder exists
output_folder = "./given_data/cityline_geojson_reprojected"
os.makedirs(output_folder, exist_ok=True)

# Get all filenames in the folder
file_names = os.listdir(folder_path)

# Filter for GeoJSON files (optional)
geojson_files = [f for f in file_names if f.endswith(".geojson")]

for file_name in geojson_files:
    # Load the GeoJSON data
    input_file_path = os.path.join(folder_path, file_name)
    with open(input_file_path, "r") as f:
        geojson_data = json.load(f)

    # Initialize the transformer (EPSG:3857 to EPSG:4326)
    transformer = Transformer.from_crs("EPSG:3857", "EPSG:4326", always_xy=True)

    # Reproject the coordinates
    for feature in geojson_data["features"]:
        geom_type = feature["geometry"]["type"]
        coords = feature["geometry"]["coordinates"]

        if geom_type == "Point":
            # Transform Point coordinates
            x, y = coords
            lon, lat = transformer.transform(x, y)
            feature["geometry"]["coordinates"] = [lon, lat]
        elif geom_type == "LineString":
            # Transform LineString coordinates
            feature["geometry"]["coordinates"] = [
                transformer.transform(x, y) for x, y in coords
            ]
        elif geom_type == "Polygon":
            # Transform Polygon coordinates (outer ring and possible inner rings)
            feature["geometry"]["coordinates"] = [
                [transformer.transform(x, y) for x, y in ring] for ring in coords
            ]

    # Update the CRS to EPSG:4326
    geojson_data["crs"] = {
        "type": "name",
        "properties": {"name": "urn:ogc:def:crs:EPSG::4326"},
    }

    # Save the reprojected GeoJSON
    output_file_path = os.path.join(output_folder, file_name)
    with open(output_file_path, "w") as f:
        json.dump(geojson_data, f, indent=2)

    print(f"Reprojection complete! Saved to {output_file_path}.")
